---
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Apache
    apt:
      name: "{{ apache_packages }}"
      state: present

  - name: Install MySQL
    apt:
      name: "{{ mysql_packages }}"
      state: present

  - name: Install PHP
    apt:
      name: "{{ php_packages }}"
      state: present

  - name: Install Python3 and pip3
    apt:
      name:
        - python3
        - python3-pip
      state: present

  - name: Ensure PyMySQL is installed
    pip:
      name: pymysql
      state: present
      executable: pip3

  - name: Create Mysql configuration file
    template:
      src: my.cnf.j2
      dest: /etc/mysql/my.cnf

  # - name: Debug mysql_root_password
  #   debug:
  #     var: mysql_root_password

  - name: Create /root/.my.cnf for MySQL root login
    copy:
      content: |
        [client]
        user=root
        password={{ mysql_root_password }}
      dest: /root/.my.cnf
      mode: '0600'

  - name: Ensure MySQL service is started
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Check root user's authentication method
    command: |
      mysql -NBe "SELECT plugin FROM mysql.user WHERE User='root' AND Host='localhost';"
    become: yes
    become_method: sudo
    register: root_auth_method
    ignore_errors: true

  - name: Change root user auth method to mysql_native_password
    command: |
      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '{{ mysql_root_password }}';"
    become: yes
    become_method: sudo
    when: root_auth_method.stdout == 'auth_socket'


  - name: Create a new MySQL database
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: "{{ new_database }}"
      state: present
    become: yes
    become_method: sudo

  - name: Create a new MySQL user
    mysql_user:
      name: "{{ new_user }}"
      password: "{{ new_user_password }}"
      priv: "*.*:ALL"
      host: '%'
      state: present



