---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: 
        update_cache: yes
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Update yum cache.
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

  roles:
    - role: roles/setup_bashrc 
    - role: roles/install_kubectl
    - role: roles/install_krew
    - role: roles/install_krew_plugins
    - role: roles/install_terraform
    - role: roles/install_packer
    - role: roles/install_vargant
    - role: roles/install_helm
    - role: roles/install_pulumi
    - role: roles/install_kustomize
