---
galaxy_info:
  author: somaz
  description: Ansible role to install setup_bashrc
  license: MIT
  min_ansible_version: 2.9
  role_name: setup_bashrc
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: RHEL
      versions:
        - all
    - name: CentOS
      versions:
        - all
  galaxy_tags:
    - setup_bashrc

dependencies: []
