---
- name: Check if Helm is installed
  command: helm version --client
  register: helm_check
  failed_when: false
  changed_when: false

- name: Check if Packer is installed
  command: packer --version
  register: packer_check
  failed_when: false
  changed_when: false

- name: Check if Terraform is installed
  command: terraform --version
  register: terraform_check
  failed_when: false
  changed_when: false

- name: Download and install Helm
  shell: "curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
  when: helm_check.rc != 0

- name: Install Packer for Debian/Ubuntu
  block:
    - name: Add HashiCorp GPG key
      shell: "curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -"
    - name: Add HashiCorp repository
      shell: "sudo apt-add-repository \"deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main\""
    - name: Update apt and install Packer
      apt:
        name: packer
        update_cache: yes
  when: ansible_os_family == 'Debian' and packer_check.rc != 0

- name: Install Terraform for Debian/Ubuntu
  block:
    - name: Add required tools and HashiCorp GPG key
      shell: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
    - name: Add HashiCorp repository
      shell: "echo \"deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main\" | sudo tee /etc/apt/sources.list.d/hashicorp.list"
    - name: Update apt and install Terraform
      apt:
        name: terraform
        update_cache: yes
  when: ansible_os_family == 'Debian' and terraform_check.rc != 0

- name: Install Packer for RHEL
  block:
    - name: Setup HashiCorp repo for Packer
      shell: "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
    - name: Install Packer
      yum:
        name: packer
        state: present
  when: ansible_os_family == 'RedHat' and packer_check.rc != 0

- name: Install Terraform for RHEL
  block:
    - name: Setup HashiCorp repo for Terraform
      shell: "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
    - name: Install Terraform
      yum:
        name: terraform
        state: present
  when: ansible_os_family == 'RedHat' and terraform_check.rc != 0
