---
- name: Check if Helm is installed
  command: which helm
  register: helm_check
  failed_when: false
  changed_when: false

- name: Download and install Helm Debian/Ubuntu
  shell: "curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
  when: 
    - ansible_os_family == 'Debian'
    - helm_check.rc != 0

- name: Download and install Helm RHEL/CentOS
  shell: "export PATH=$PATH:/usr/local/bin && curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
  when: 
    - ansible_os_family == 'RedHat'
    - helm_check.rc != 0