---
- name: Check if Vagrant is installed
  command: which vagrant
  register: vagrant_check
  failed_when: false
  changed_when: false

- name: Install yum-utils RHEL/CentOS
  yum:
    name: yum-utils 
    state: present
  become: yes
  when: ansible_os_family == 'RedHat' and vagrant_check.rc != 0

- name: Install Vagrant for Debian/Ubuntu
  block:
    - name: Add HashiCorp GPG key (Debian/Ubuntu)
      shell: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
    - name: Add HashiCorp repository (Debian/Ubuntu)
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    - name: Update apt and install Vagrant for (Debian/Ubuntu)
      apt:
        name: vagrant
        update_cache: yes
  when: ansible_os_family == 'Debian' and vagrant_check.rc != 0

- name: Install Vagrant for RHEL/CentOS
  block:
    - name: Setup HashiCorp repo for Vagrant (RHEL/CentOS)
      shell: "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
    - name: Install Vagrant (RHEL/CentOS)
      yum:
        name: vagrant
        state: present
  when: ansible_os_family == 'RedHat' and vagrant_check.rc != 0

